### Exercise 5.25

Revise your program from the previous exercise to use a `try` block to `catch`
the exception. The `catch` clause should print a message to the user and ask
them to supply a ew number and repeate the code inside the `try`.

### Solution

See `25.cc`.
